name: drupal8-startup

# Configure the Drupal8 recipe
recipe: drupal8
config:
  php: '7.2'
  via: nginx
  webroot: docroot
  drush: composer
  database: mariadb:10.1
  xdebug: true

# Service overrides and augments
# See: https://docs.devwithlando.io/config/services.html
services:

  appserver:
    build:
      - cd $LANDO_MOUNT && composer install

#  Optional - for Acquia hosting.
#  cache:
#    type: memcached
#    mem: 128

  cache:
    type: redis
    persist: true

# Add an indexing backend
# See: https://docs.devwithlando.io/services/solr.html

# Acquia currently only supports 4.10
#  search:
#    type: solr:4.10
#    config:
#      conf: "docroot/modules/contrib/search_api_solr/solr-conf/4.x"

# Platform.sh supports up to 6.6
#  search:
#    type: solr:6.6
#    config:
#      conf: "docroot/modules/contrib/search_api_solr/solr-conf/6.x

  # Add mailhog capturing
  # See: https://docs.devwithlando.io/services/mailhog.html
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  node:
    type: node
    globals:
      gulp: latest
      gulp-cli: latest
    # Replace this with your theme path after it's been generated.
    # build:
    #   - cd /app/docroot/themes/custom/startup_theme && npm install
    ports: [3000:3000]

# Additional mailhog proxy settings so we get a nice URL for the mailhog ui
proxy:
  mailhog:
    - mail.startup.lndo.site
  nginx:
    - www.startup.lndo.site
  node:
    - fractal.lndo.site:3000

# Development tools
tooling:
  install:
    descripion: Install/Re-install Site
    service: appserver
    cmd: ./scripts/install.sh

  refresh:
    descripion: Refresh (composer install, reload config, clear cache, etc.)
    service: appserver
    cmd: ./scripts/development/refresh.sh

  reset:
    description: Reset repo (remove generated files).
    service: appserver
    cmd: ./scripts/development/reset.sh

  phpcs:
    description: Run PHP Code Sniffer
    service: appserver
    cmd: ./bin/phpcs

  phpunit:
    description: Run PHPUnit
    service: appserver
    cmd: ./bin/phpunit

  behat:
    description: Run Behat
    service: appserver
    cmd:
      - ./bin/behat
      - -vv
      - --config=test/behat/behat.yml

  test:
    description: Run all tests
    service: appserver
    cmd: ./scripts/development/tests.sh

  npm:
    service: node
    cmd: npm
