language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer

env:
  global:
      - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress"
      - COMPOSER_FLAGS=""

services:
  - docker

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

  # Install Lando.
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.35/lando-v3.0.0-beta.35.deb
  - sudo dpkg -i /tmp/lando.deb

  # Sanity check to make sure we are rolling.
  - lando version

    # Composer: boost installation
    - lando composer global show hirak/prestissimo -q || travis_retry lando composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

script:

  # Start & build.
  - lando start -- -v

  # Run Coding style.
  - ./bin/phpcs

  # Run Unit/Kernel tests.
  - ./bin/phpunit

  # Install site.
  # TODO: retrieve sanitized db snapshot / install w/ default content.
  - lando install -- -v

  # Integration tests
  # - ./bin/behat